<?php
$pageTitle = "Subscription Management Software – Automate Recurring Billing & Renewals | ZYLO CRM";
$pageDescription = "ZYLO's subscription management software automates recurring billing, renewal reminders, plan upgrades/downgrades, and churn tracking. GST-ready. Free plan available. Trusted by 10,000+ businesses.";
$pageKeywords = "subscription management software India, recurring billing software, subscription billing software, SaaS billing software India, subscription invoicing software, renewal management software, subscription tracking software";
$canonicalPath = '/subscription-management-software';

$pageSchema = [
    '@context' => 'https://schema.org',
    '@type'    => 'SoftwareApplication',
    'name'     => 'ZYLO Subscription Management Software',
    'url'      => 'https://zylocrm.com/subscription-management-software',
    'description' => 'Subscription management software for Indian businesses. Automate recurring billing, send renewal reminders, handle plan changes, track MRR and churn — all with GST-compliant invoicing.',
    'applicationCategory' => 'BusinessApplication',
    'operatingSystem' => 'Web, Android, iOS',
    'provider' => [
        '@type' => 'Organization',
        'name'  => 'ZYLO CRM',
        'url'   => 'https://zylocrm.com',
        'logo'  => 'https://zylocrm.com/assets/logo.png'
    ],
    'offers' => [
        '@type'         => 'Offer',
        'priceCurrency' => 'INR',
        'price'         => '0',
        'description'   => 'Free plan available. Pro plan from ₹3,999/month.',
        'pricingModel'  => 'Freemium'
    ],
    'aggregateRating' => [
        '@type'       => 'AggregateRating',
        'ratingValue' => '4.8',
        'reviewCount' => '318',
        'bestRating'  => '5'
    ],
    'featureList' => [
        'Automated recurring invoice generation',
        'Subscription renewal reminders via WhatsApp and email',
        'Plan upgrade and downgrade management',
        'Trial period and free plan management',
        'MRR and ARR tracking dashboard',
        'Churn rate monitoring and alerts',
        'Prorated billing on plan changes',
        'GST-compliant subscription invoicing'
    ]
];

$faqSchema = [
    '@context'   => 'https://schema.org',
    '@type'      => 'FAQPage',
    'mainEntity' => [
        [
            '@type' => 'Question',
            'name'  => 'What is subscription management software?',
            'acceptedAnswer' => ['@type' => 'Answer', 'text' => 'Subscription management software automates the entire lifecycle of recurring revenue — from generating invoices on schedule, sending renewal reminders, handling plan upgrades and downgrades, tracking MRR and churn, to collecting payments automatically. It eliminates the manual work of managing recurring clients.']
        ],
        [
            '@type' => 'Question',
            'name'  => 'Is ZYLO subscription management software free?',
            'acceptedAnswer' => ['@type' => 'Answer', 'text' => 'Yes. ZYLO offers a free plan with basic recurring billing for up to 10 active subscriptions. The Pro plan starts at ₹3,999/month with unlimited subscriptions, automated renewal reminders, MRR/ARR dashboards, churn tracking, and WhatsApp notifications.']
        ],
        [
            '@type' => 'Question',
            'name'  => 'Can ZYLO handle GST on subscription invoices?',
            'acceptedAnswer' => ['@type' => 'Answer', 'text' => 'Yes. Every recurring invoice generated by ZYLO is fully GST-compliant. The system auto-applies the correct GST rate per subscription plan, splits CGST/SGST or IGST based on the customer\'s state, and generates GSTR-ready reports automatically.']
        ],
        [
            '@type' => 'Question',
            'name'  => 'Can I manage trial periods and free plans?',
            'acceptedAnswer' => ['@type' => 'Answer', 'text' => 'Yes. ZYLO lets you configure trial periods (7, 14, or 30 days) for any plan. Trial customers are tracked separately, receive automated upgrade prompts as the trial expires, and convert to paid subscriptions automatically when they choose a plan.']
        ],
        [
            '@type' => 'Question',
            'name'  => 'Does ZYLO track MRR, ARR, and churn?',
            'acceptedAnswer' => ['@type' => 'Answer', 'text' => 'Yes. ZYLO\'s subscription dashboard shows MRR (Monthly Recurring Revenue), ARR (Annual Recurring Revenue), new MRR, expansion MRR, churned MRR, and net revenue retention — updated in real time as subscriptions change.']
        ]
    ]
];

include 'includes/header.php';
?>
<script type="application/ld+json"><?php echo json_encode($faqSchema, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE); ?></script>

<!-- ========== HERO ========== -->
<section class="bg-offwhite" style="padding-top:calc(var(--header-height) + 4.5rem); padding-bottom:5rem; position:relative; overflow:hidden;">
    <div style="position:absolute;top:-15%;right:-8%;width:520px;height:520px;background:radial-gradient(circle,rgba(12,79,120,0.07) 0%,transparent 70%);border-radius:50%;pointer-events:none;" aria-hidden="true"></div>

    <div class="container">
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:4rem;align-items:center;" class="intro-grid">
            <div>
                <div style="display:inline-flex;align-items:center;gap:0.5rem;background:rgba(12,79,120,0.08);color:var(--primary);font-size:0.8rem;font-weight:700;padding:0.38rem 1rem;border-radius:50px;margin-bottom:1.5rem;text-transform:uppercase;letter-spacing:1px;border:1px solid rgba(12,79,120,0.18);">
                    <span style="width:7px;height:7px;background:#22c55e;border-radius:50%;display:inline-block;animation:pulse-dot 2s ease-in-out infinite;"></span>
                    Zero Manual Billing Work
                </div>

                <h1 style="font-size:3.2rem;color:var(--primary-dark);line-height:1.12;margin-bottom:1.4rem;">
                    Subscription Management Software That Bills Itself
                </h1>
                <p style="font-size:1.18rem;line-height:1.8;color:var(--text-muted);margin-bottom:1.9rem;">
                    Automate every recurring invoice, renewal reminder, plan change, and payment collection. Track MRR, ARR, and churn in real time — while ZYLO handles all the billing work in the background.
                </p>

                <div style="display:flex;flex-wrap:wrap;gap:0.55rem;margin-bottom:2rem;">
                    <?php foreach(['Auto Recurring Billing','Renewal Reminders','MRR & ARR Tracking','Churn Monitoring','GST Invoices','Free Plan'] as $p): ?>
                    <span style="background:white;border:1px solid var(--border-color);color:var(--text-main);font-size:0.82rem;font-weight:600;padding:0.35rem 0.9rem;border-radius:50px;box-shadow:var(--shadow-sm);">✓ &nbsp;<?= $p ?></span>
                    <?php endforeach; ?>
                </div>

                <div style="display:flex;gap:1rem;flex-wrap:wrap;">
                    <a href="contact" class="btn btn-primary" style="padding:0.9rem 2rem;font-size:1rem;">Start Free Trial</a>
                    <a href="#features" class="btn btn-outline" style="padding:0.9rem 2rem;font-size:1rem;">See All Features</a>
                </div>
                <p style="margin-top:1.5rem;font-size:0.85rem;color:var(--text-muted);margin-bottom:0;">
                    ⭐ 4.8/5 from 318 reviews &nbsp;·&nbsp; Trusted by 10,000+ businesses
                </p>
            </div>

            <div style="position:relative;">
                <img src="assets/store/section-1.jpg"
                     alt="ZYLO subscription management software dashboard showing MRR growth and active subscriptions"
                     width="580" height="400"
                     style="width:100%;border-radius:20px;box-shadow:var(--shadow-xl);display:block;"
                     fetchpriority="high">

                <!-- Floating: Invoice auto-sent -->
                <div style="position:absolute;top:-1rem;left:-1.25rem;background:white;border-radius:14px;padding:0.85rem 1.1rem;box-shadow:var(--shadow-lg);border:1px solid var(--border-color);display:flex;align-items:center;gap:0.7rem;">
                    <span style="width:36px;height:36px;background:#dcfce7;border-radius:9px;display:flex;align-items:center;justify-content:center;flex-shrink:0;">
                        <svg width="17" height="17" fill="none" stroke="#16a34a" stroke-width="2" viewBox="0 0 24 24" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
                    </span>
                    <div>
                        <div style="font-size:0.75rem;color:var(--text-muted);">Auto-billed this month</div>
                        <div style="font-size:0.88rem;font-weight:700;color:#16a34a;">124 subscriptions · ₹4.8L</div>
                    </div>
                </div>

                <!-- Floating: MRR -->
                <div style="position:absolute;bottom:-1.25rem;right:-1rem;background:white;border-radius:14px;padding:0.85rem 1.1rem;box-shadow:var(--shadow-lg);border:1px solid var(--border-color);display:flex;align-items:center;gap:0.7rem;">
                    <span style="width:36px;height:36px;background:rgba(12,79,120,0.08);border-radius:9px;display:flex;align-items:center;justify-content:center;flex-shrink:0;">
                        <svg width="17" height="17" fill="none" stroke="var(--primary)" stroke-width="2" viewBox="0 0 24 24" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6"/></svg>
                    </span>
                    <div>
                        <div style="font-size:0.75rem;color:var(--text-muted);">MRR this month</div>
                        <div style="font-size:0.88rem;font-weight:700;color:var(--text-main);">₹4,84,000 <span style="color:#16a34a;font-size:0.78rem;">↑ 18%</span></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<style>
@keyframes pulse-dot {
    0%,100%{opacity:1;transform:scale(1);}
    50%{opacity:0.5;transform:scale(1.5);}
}
</style>

<!-- ========== STATS BAR ========== -->
<section style="padding:2.75rem 0;background:white;border-bottom:1px solid var(--border-color);">
    <div class="container">
        <div style="display:grid;grid-template-columns:repeat(4,1fr);gap:1rem;text-align:center;" class="stats-bar-grid">
            <?php
            $stats = [
                ['val'=>'Zero',  'label'=>'Manual Invoice Work Per Month'],
                ['val'=>'98%',   'label'=>'On-Time Renewal Rate'],
                ['val'=>'Real-Time','label'=>'MRR & Churn Dashboard'],
                ['val'=>'10,000+','label'=>'Businesses Trust ZYLO'],
            ];
            foreach($stats as $i=>$s):
                $b=$i>0?'border-left:1px solid var(--border-color);':'';
            ?>
            <div style="<?= $b ?>">
                <div style="font-size:2rem;font-weight:800;color:var(--primary-dark);line-height:1;margin-bottom:0.4rem;"><?= $s['val'] ?></div>
                <div style="font-size:0.83rem;color:var(--text-muted);"><?= $s['label'] ?></div>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
</section>

<!-- ========== INTRO ========== -->
<section>
    <div class="container">
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:5rem;align-items:center;" class="intro-grid">
            <div>
                <div style="display:inline-block;background:rgba(12,79,120,0.08);color:var(--primary);font-size:0.78rem;font-weight:700;padding:0.3rem 0.85rem;border-radius:50px;margin-bottom:1.25rem;text-transform:uppercase;letter-spacing:1px;">Recurring Revenue</div>
                <h2 style="font-size:2.2rem;color:var(--primary-dark);line-height:1.25;margin-bottom:1.25rem;">
                    Your Subscriptions Run Themselves. You Focus on Growth.
                </h2>
                <p style="font-size:1.05rem;line-height:1.8;color:var(--text-muted);margin-bottom:1.5rem;">
                    ZYLO handles every recurring billing task automatically — generate invoices on schedule, send renewal reminders before they lapse, collect payments, and handle plan changes with prorated adjustments.
                </p>
                <p style="font-size:1.05rem;line-height:1.8;color:var(--text-muted);margin-bottom:1.75rem;">
                    While you focus on acquiring new customers, ZYLO makes sure every existing subscriber is billed on time, every time — with zero manual effort from your team.
                </p>

                <div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin-bottom:1.75rem;">
                    <?php
                    $metrics = [
                        ['val'=>'Zero',    'label'=>'manual billing tasks'],
                        ['val'=>'98%',     'label'=>'on-time renewal rate'],
                        ['val'=>'< 2 min', 'label'=>'to add a new subscriber'],
                        ['val'=>'Real-Time','label'=>'MRR & churn visibility'],
                    ];
                    foreach($metrics as $m): ?>
                    <div style="background:var(--bg-offwhite);border:1px solid var(--border-color);border-radius:12px;padding:0.9rem 1rem;">
                        <div style="font-size:1.35rem;font-weight:800;color:var(--primary-dark);margin-bottom:0.2rem;"><?= $m['val'] ?></div>
                        <div style="font-size:0.8rem;color:var(--text-muted);"><?= $m['label'] ?></div>
                    </div>
                    <?php endforeach; ?>
                </div>
                <a href="contact" class="btn btn-primary" style="padding:0.75rem 1.75rem;">Start Free — No Card Needed</a>
            </div>

            <div style="position:relative;">
                <img src="assets/store/section-2.jpg"
                     alt="ZYLO subscription billing dashboard showing active subscriptions and renewal schedule"
                     width="560" height="380"
                     style="width:100%;border-radius:20px;box-shadow:var(--shadow-xl);display:block;" loading="lazy">
                <div style="position:absolute;bottom:-1rem;right:-1rem;background:white;border-radius:12px;padding:0.85rem 1.1rem;box-shadow:var(--shadow-lg);border:1px solid var(--border-color);">
                    <div style="font-size:0.75rem;color:var(--text-muted);margin-bottom:0.2rem;">Renewal reminder sent</div>
                    <div style="font-size:0.88rem;font-weight:700;color:var(--text-main);">18 subscribers · 3 days left</div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- ========== KEY FEATURES ========== -->
<section id="features" class="bg-offwhite">
    <div class="container">
        <div class="section-title">
            <h2>Complete Subscription Lifecycle Management</h2>
            <p>From trial to renewal to cancellation — ZYLO handles every stage automatically.</p>
        </div>

        <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:1.75rem;margin-top:3rem;" class="features-grid">
            <?php
            $features = [
                [
                    'icon'  => 'M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15',
                    'title' => 'Automated Recurring Billing',
                    'desc'  => 'Set a billing schedule once — weekly, monthly, quarterly, or annual. ZYLO generates and sends GST-compliant invoices automatically on the billing date, every cycle, without exception.',
                    'pts'   => ['Any billing frequency','GST invoice auto-generated','Email + WhatsApp delivery']
                ],
                [
                    'icon'  => 'M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9',
                    'title' => 'Renewal Reminders & Dunning',
                    'desc'  => 'Send automated reminders before renewal dates via WhatsApp and email. Smart dunning sequences follow up on failed payments — recover revenue before subscriptions lapse.',
                    'pts'   => ['Pre-renewal WhatsApp alerts','Failed payment dunning','Auto-suspend on non-renewal']
                ],
                [
                    'icon'  => 'M7 16V4m0 0L3 8m4-4l4 4M17 8v12m0 0l4-4m-4 4l-4-4',
                    'title' => 'Plan Upgrades & Downgrades',
                    'desc'  => 'Subscribers can upgrade or downgrade anytime. ZYLO calculates prorated amounts automatically, generates an adjustment invoice, and updates the billing schedule — instantly and accurately.',
                    'pts'   => ['Proration auto-calculated','Adjustment invoice generated','Billing schedule updated instantly']
                ],
                [
                    'icon'  => 'M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z',
                    'title' => 'Trial Period Management',
                    'desc'  => 'Configure trial lengths for any plan. Trial users are tracked separately, receive automated "trial ending" alerts, and convert to paid automatically when they choose a plan.',
                    'pts'   => ['Configurable trial lengths','Trial expiry reminders','Auto-convert to paid plan']
                ],
                [
                    'icon'  => 'M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z',
                    'title' => 'MRR, ARR & Revenue Metrics',
                    'desc'  => 'Real-time dashboard shows MRR, ARR, new MRR, expansion MRR, churned MRR, and Net Revenue Retention — so you always know the health of your recurring revenue.',
                    'pts'   => ['MRR & ARR live dashboard','New vs expansion vs churned','Net revenue retention (NRR)']
                ],
                [
                    'icon'  => 'M13 17h8m0 0V9m0 8l-8-8-4 4-6-6',
                    'title' => 'Churn Monitoring & Alerts',
                    'desc'  => 'Track churn rate in real time. Get alerts when high-value subscribers are at risk — based on engagement signals — so your team can intervene before cancellations happen.',
                    'pts'   => ['Real-time churn rate tracking','At-risk subscriber alerts','Cancellation reason capture']
                ],
                [
                    'icon'  => 'M9 14l6-6m-5.5.5h.01m4.99 5h.01M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16l3.5-2 3.5 2 3.5-2 3.5 2z',
                    'title' => 'GST-Compliant Invoicing',
                    'desc'  => 'Every recurring invoice is fully GST-compliant — auto CGST/SGST/IGST split, HSN/SAC codes, and GSTR-ready export. Supports e-Invoice with IRN for eligible businesses.',
                    'pts'   => ['Auto CGST/SGST/IGST','GSTR-1 ready reports','e-Invoice + IRN support']
                ],
                [
                    'icon'  => 'M17 9V7a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2m2 4h10a2 2 0 002-2v-6a2 2 0 00-2-2H9a2 2 0 00-2 2v6a2 2 0 002 2zm7-5a2 2 0 11-4 0 2 2 0 014 0z',
                    'title' => 'Online Payment Collection',
                    'desc'  => 'Every recurring invoice includes a "Pay Now" link. Subscribers pay via UPI, net banking, or cards. ZYLO marks the invoice paid, updates subscription status, and notifies your team instantly.',
                    'pts'   => ['UPI, cards, net banking','Auto mark-paid on receipt','Payment confirmation alerts']
                ],
                [
                    'icon'  => 'M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15',
                    'title' => 'Pause & Resume Subscriptions',
                    'desc'  => 'Subscribers can pause subscriptions for a defined period. ZYLO stops billing during the pause, resumes automatically when the period ends, and adjusts the renewal date — no manual intervention needed.',
                    'pts'   => ['Subscriber-initiated pauses','Auto-resume on pause end','Pause period billing adjustment']
                ],
            ];
            foreach($features as $f): ?>
            <div class="card" style="padding:2rem;border-left:3px solid var(--primary);display:flex;flex-direction:column;">
                <div style="width:48px;height:48px;background:rgba(12,79,120,0.08);border-radius:10px;display:flex;align-items:center;justify-content:center;margin-bottom:1.25rem;color:var(--primary);flex-shrink:0;">
                    <svg width="23" height="23" fill="none" stroke="currentColor" stroke-width="1.8" viewBox="0 0 24 24" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="<?= $f['icon'] ?>"/></svg>
                </div>
                <h3 style="font-size:1.1rem;color:var(--primary-dark);margin-bottom:0.7rem;"><?= $f['title'] ?></h3>
                <p style="color:var(--text-muted);font-size:0.92rem;line-height:1.7;margin-bottom:1rem;flex:1;"><?= $f['desc'] ?></p>
                <ul style="list-style:none;padding:0;margin:0;">
                    <?php foreach($f['pts'] as $pt): ?>
                    <li style="display:flex;align-items:center;gap:0.5rem;font-size:0.84rem;color:var(--text-muted);margin-bottom:0.35rem;">
                        <svg width="13" height="13" fill="none" stroke="#22c55e" stroke-width="2.5" viewBox="0 0 24 24" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7"/></svg>
                        <?= $pt ?>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
</section>

<!-- ========== SUBSCRIPTION LIFECYCLE ========== -->
<section>
    <div class="container">
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:5rem;align-items:center;" class="intro-grid">
            <div>
                <div style="display:inline-block;background:rgba(12,79,120,0.08);color:var(--primary);font-size:0.78rem;font-weight:700;padding:0.3rem 0.85rem;border-radius:50px;margin-bottom:1.25rem;text-transform:uppercase;letter-spacing:1px;">Full Lifecycle</div>
                <h2 style="font-size:2.2rem;color:var(--primary-dark);line-height:1.25;margin-bottom:1.25rem;">
                    Every Subscription Stage — Fully Automated
                </h2>
                <p style="font-size:1.05rem;line-height:1.8;color:var(--text-muted);margin-bottom:1.75rem;">
                    From the moment a subscriber signs up to every renewal, upgrade, pause, and eventual cancellation — ZYLO manages the entire lifecycle without any manual intervention from your team.
                </p>

                <!-- Lifecycle flow -->
                <div style="background:var(--bg-offwhite);border:1px solid var(--border-color);border-radius:14px;padding:1.25rem 1.5rem;margin-bottom:1.75rem;">
                    <div style="font-size:0.8rem;font-weight:700;color:var(--primary);text-transform:uppercase;letter-spacing:1px;margin-bottom:0.85rem;">Subscription Lifecycle in ZYLO</div>
                    <?php
                    $lifecycle = [
                        ['icon'=>'M18 9v3m0 0v3m0-3h3m-3 0h-3m-2-5a4 4 0 11-8 0 4 4 0 018 0zM3 20a6 6 0 0112 0v1H3v-1z', 'color'=>'var(--primary)', 'text'=>'Subscriber added → trial or active plan begins'],
                        ['icon'=>'M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z', 'color'=>'#0ea5e9', 'text'=>'Invoice auto-generated on billing date'],
                        ['icon'=>'M12 19l9 2-9-18-9 18 9-2zm0 0v-8',             'color'=>'#8b5cf6', 'text'=>'Invoice sent via email & WhatsApp'],
                        ['icon'=>'M17 9V7a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2m2 4h10','color'=>'#f59e0b', 'text'=>'Payment collected → subscription renewed'],
                        ['icon'=>'M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11','color'=>'#ef4444', 'text'=>'On non-payment: dunning sequence triggered'],
                        ['icon'=>'M7 16V4m0 0L3 8m4-4l4 4M17 8v12m0 0l4-4m-4 4l-4-4','color'=>'#16a34a', 'text'=>'Plan changed → proration calculated auto'],
                    ];
                    foreach($lifecycle as $i=>$lc): ?>
                    <div style="display:flex;align-items:center;gap:0.75rem;padding:0.6rem 0;<?= $i<count($lifecycle)-1?'border-bottom:1px solid var(--border-color);':'' ?>">
                        <span style="width:30px;height:30px;background:<?= $lc['color'] ?>;border-radius:50%;display:flex;align-items:center;justify-content:center;flex-shrink:0;">
                            <svg width="14" height="14" fill="none" stroke="white" stroke-width="2" viewBox="0 0 24 24" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="<?= $lc['icon'] ?>"/></svg>
                        </span>
                        <span style="font-size:0.88rem;color:var(--text-main);"><?= $lc['text'] ?></span>
                    </div>
                    <?php endforeach; ?>
                </div>
                <a href="contact" class="btn btn-primary" style="padding:0.75rem 1.75rem;">Start Automating Billing</a>
            </div>

            <div style="position:relative;">
                <img src="assets/store/hero-1.jpg"
                     alt="ZYLO subscription lifecycle dashboard showing billing automation and renewal tracking"
                     width="560" height="380"
                     style="width:100%;border-radius:20px;box-shadow:var(--shadow-xl);display:block;" loading="lazy">
                <div style="position:absolute;top:-1rem;right:-1rem;background:white;border-radius:12px;padding:0.85rem 1.1rem;box-shadow:var(--shadow-lg);border:1px solid var(--border-color);">
                    <div style="font-size:0.75rem;color:var(--text-muted);margin-bottom:0.2rem;">Next billing cycle</div>
                    <div style="font-size:0.88rem;font-weight:700;color:var(--text-main);">42 invoices · 1st Jul</div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- ========== MRR DASHBOARD SPOTLIGHT ========== -->
<section class="bg-offwhite">
    <div class="container">
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:5rem;align-items:center;" class="intro-grid">
            <div style="order:2;" class="feature-img-right">
                <div style="position:relative;">
                    <img src="assets/store/section-1.jpg"
                         alt="ZYLO MRR ARR churn dashboard showing subscription revenue metrics"
                         width="560" height="380"
                         style="width:100%;border-radius:20px;box-shadow:var(--shadow-xl);display:block;" loading="lazy">
                    <div style="position:absolute;bottom:-1rem;left:-1rem;background:white;border-radius:12px;padding:0.85rem 1.1rem;box-shadow:var(--shadow-lg);border:1px solid var(--border-color);">
                        <div style="font-size:0.75rem;color:var(--text-muted);margin-bottom:0.2rem;">Churn rate this month</div>
                        <div style="font-size:0.88rem;font-weight:700;color:#16a34a;">1.8% <span style="font-size:0.78rem;color:#16a34a;">↓ 0.4%</span></div>
                    </div>
                </div>
            </div>
            <div style="order:1;">
                <div style="display:inline-block;background:rgba(12,79,120,0.08);color:var(--primary);font-size:0.78rem;font-weight:700;padding:0.3rem 0.85rem;border-radius:50px;margin-bottom:1.25rem;text-transform:uppercase;letter-spacing:1px;">Revenue Metrics</div>
                <h2 style="font-size:2.2rem;color:var(--primary-dark);line-height:1.25;margin-bottom:1.25rem;">
                    Know Your MRR, ARR, and Churn at a Glance
                </h2>
                <p style="font-size:1.05rem;line-height:1.8;color:var(--text-muted);margin-bottom:1.5rem;">
                    ZYLO's subscription dashboard gives you a live view of your recurring revenue health — not just invoices, but the metrics that matter: MRR growth, expansion revenue, churned revenue, and Net Revenue Retention.
                </p>
                <p style="font-size:1.05rem;line-height:1.8;color:var(--text-muted);margin-bottom:1.75rem;">
                    Understand which plans drive the most revenue, which cohorts have the highest churn, and where to focus to grow NRR — all without building a spreadsheet or waiting for a monthly report.
                </p>

                <!-- Metric tiles -->
                <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:0.75rem;margin-bottom:1.75rem;">
                    <?php
                    $metrics = [
                        ['label'=>'MRR',  'val'=>'₹4.84L', 'sub'=>'↑ 18% MoM', 'color'=>'#dcfce7','tc'=>'#16a34a'],
                        ['label'=>'ARR',  'val'=>'₹58L',   'sub'=>'annualised', 'color'=>'#dbeafe','tc'=>'#3b82f6'],
                        ['label'=>'Churn','val'=>'1.8%',   'sub'=>'↓ 0.4%',    'color'=>'#f0fdf4','tc'=>'#16a34a'],
                        ['label'=>'New MRR','val'=>'₹62K', 'sub'=>'this month', 'color'=>'#ede9fe','tc'=>'#8b5cf6'],
                        ['label'=>'Exp. MRR','val'=>'₹18K','sub'=>'upgrades',   'color'=>'#fef9c3','tc'=>'#ca8a04'],
                        ['label'=>'NRR',  'val'=>'108%',   'sub'=>'net retention','color'=>'#dcfce7','tc'=>'#16a34a'],
                    ];
                    foreach($metrics as $m): ?>
                    <div style="background:<?= $m['color'] ?>;border-radius:12px;padding:0.85rem;text-align:center;">
                        <div style="font-size:0.72rem;font-weight:700;color:var(--text-muted);margin-bottom:0.2rem;"><?= $m['label'] ?></div>
                        <div style="font-size:1.1rem;font-weight:800;color:var(--primary-dark);"><?= $m['val'] ?></div>
                        <div style="font-size:0.72rem;color:<?= $m['tc'] ?>;font-weight:600;"><?= $m['sub'] ?></div>
                    </div>
                    <?php endforeach; ?>
                </div>
                <a href="contact" class="btn btn-outline" style="padding:0.75rem 1.75rem;">See Dashboard Demo</a>
            </div>
        </div>
    </div>
</section>

<!-- ========== WHO IT'S FOR ========== -->
<section>
    <div class="container">
        <div class="section-title">
            <h2>Built for Every Recurring Revenue Business</h2>
            <p>Whether you charge monthly retainers or annual SaaS fees — ZYLO handles it all.</p>
        </div>

        <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:1.75rem;margin-top:3rem;" class="perfect-for-grid">
            <?php
            $personas = [
                [
                    'icon'  => 'M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z',
                    'title' => 'SaaS & Software Businesses',
                    'desc'  => 'Automate monthly/annual plan billing, manage trials, handle upgrades with prorations, and track MRR/ARR with the metrics investors and founders care about most.',
                    'link'  => 'startups',
                    'pts'   => ['Trial to paid conversion','Proration on plan changes','MRR & NRR dashboards']
                ],
                [
                    'icon'  => 'M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z',
                    'title' => 'Consultants & Agencies',
                    'desc'  => 'Bill all your retainer clients automatically on the 1st of every month. No more manually creating invoices. Never miss a billing cycle. Spend time on client work, not billing admin.',
                    'link'  => 'consultants',
                    'pts'   => ['Monthly retainer automation','Per-client billing schedules','Renewal reminder via WhatsApp']
                ],
                [
                    'icon'  => 'M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253',
                    'title' => 'Membership & EdTech',
                    'desc'  => 'Manage membership subscriptions, course access renewals, and annual plan upgrades. Automate student billing and track cohort churn to improve retention.',
                    'link'  => 'subscription-management-software',
                    'pts'   => ['Membership plan automation','Course access billing','Cohort retention analytics']
                ],
            ];
            foreach($personas as $p): ?>
            <div class="card" style="padding:2.25rem;display:flex;flex-direction:column;">
                <div style="width:52px;height:52px;background:rgba(12,79,120,0.08);border-radius:12px;display:flex;align-items:center;justify-content:center;margin-bottom:1.25rem;color:var(--primary);">
                    <svg width="26" height="26" fill="none" stroke="currentColor" stroke-width="1.8" viewBox="0 0 24 24" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="<?= $p['icon'] ?>"/></svg>
                </div>
                <h3 style="font-size:1.2rem;color:var(--primary-dark);margin-bottom:0.75rem;"><?= $p['title'] ?></h3>
                <p style="color:var(--text-muted);font-size:0.93rem;line-height:1.7;margin-bottom:1rem;flex:1;"><?= $p['desc'] ?></p>
                <ul style="list-style:none;padding:0;margin:0 0 1.5rem;">
                    <?php foreach($p['pts'] as $pt): ?>
                    <li style="display:flex;align-items:center;gap:0.5rem;font-size:0.85rem;color:var(--text-muted);margin-bottom:0.35rem;">
                        <svg width="14" height="14" fill="none" stroke="#22c55e" stroke-width="2.5" viewBox="0 0 24 24" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7"/></svg>
                        <?= $pt ?>
                    </li>
                    <?php endforeach; ?>
                </ul>
                <a href="<?= $p['link'] ?>" style="font-weight:600;font-size:0.9rem;color:var(--primary);display:inline-flex;align-items:center;gap:0.3rem;margin-top:auto;">Learn more &rarr;</a>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
</section>

<!-- ========== COMPARISON ========== -->
<section class="bg-offwhite">
    <div class="container">
        <div class="section-title">
            <h2>ZYLO vs Other Subscription Billing Tools</h2>
            <p>See why recurring revenue businesses choose ZYLO.</p>
        </div>

        <div style="overflow-x:auto;margin-top:2.5rem;border-radius:16px;box-shadow:var(--shadow-md);border:1px solid var(--border-color);" class="comparison-table">
            <table style="width:100%;border-collapse:collapse;background:white;min-width:560px;">
                <thead>
                    <tr style="background:var(--primary);color:white;">
                        <th style="padding:1.1rem 1.5rem;text-align:left;font-weight:600;font-size:0.93rem;width:34%;">Feature</th>
                        <th style="padding:1.1rem 1.5rem;text-align:center;font-weight:700;font-size:0.93rem;">
                            <span style="background:rgba(255,255,255,0.15);padding:0.2rem 0.75rem;border-radius:50px;">ZYLO CRM</span>
                        </th>
                        <th style="padding:1.1rem 1.5rem;text-align:center;font-weight:600;font-size:0.93rem;opacity:0.8;">Other Billing Tools</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $rows = [
                        ['Free Plan',                         '✅ Forever free (10 subs)',       '❌ Trial only'],
                        ['GST-Compliant Invoicing',           '✅ Auto CGST/SGST/IGST',          '⚠️ Manual GST setup'],
                        ['WhatsApp Renewal Reminders',        '✅ Native WhatsApp integration',  '❌ Email only'],
                        ['Proration on Plan Changes',         '✅ Auto-calculated',              '⚠️ Manual or not available'],
                        ['MRR / ARR / Churn Dashboard',       '✅ Real-time built-in metrics',   '⚠️ Paid add-on'],
                        ['CRM + Inventory Bundled',           '✅ All-in-one platform',          '❌ Billing tool only'],
                        ['e-Invoice + IRN Support',           '✅ GSTN IRP integrated',          '❌ Not available for India'],
                        ['Price / Month',                     '₹0 – ₹3,999',                   '₹3,000 – ₹15,000+'],
                    ];
                    foreach($rows as $i=>$row):
                        $bg=$i%2===1?'background:#f8f9fa;':'';
                    ?>
                    <tr style="<?= $bg ?>">
                        <td style="padding:1rem 1.5rem;font-weight:600;color:var(--primary-dark);font-size:0.9rem;border-bottom:1px solid var(--border-color);"><?= $row[0] ?></td>
                        <td style="padding:1rem 1.5rem;text-align:center;font-size:0.9rem;border-bottom:1px solid var(--border-color);color:var(--primary-dark);font-weight:500;"><?= $row[1] ?></td>
                        <td style="padding:1rem 1.5rem;text-align:center;font-size:0.9rem;border-bottom:1px solid var(--border-color);color:var(--text-muted);"><?= $row[2] ?></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</section>

<!-- ========== TESTIMONIALS ========== -->
<section>
    <div class="container">
        <div class="section-title">
            <h2>What Our Customers Say</h2>
            <p>Real results from businesses that automated their subscription billing with ZYLO.</p>
        </div>

        <div class="grid-3" style="margin-top:3rem;">
            <?php
            $reviews = [
                [
                    'quote' => '"We have 80+ retainer clients and used to spend 2 days every month creating and sending invoices. ZYLO does it automatically on the 1st. My team has zero billing work now — those 2 days go into actual client work."',
                    'name'  => 'Priya Nair',
                    'role'  => 'Founder, NairTech Agency · Bengaluru',
                    'img'   => 'assets/store/avatar-sarah.jpg',
                ],
                [
                    'quote' => '"The WhatsApp renewal reminder is a game-changer. Before ZYLO, 12% of clients would forget to renew and we\'d chase them for weeks. Now they get a WhatsApp reminder 7 days before — our renewal rate went from 82% to 96%."',
                    'name'  => 'Rohan Desai',
                    'role'  => 'CEO, CloudStack SaaS · Mumbai',
                    'img'   => 'assets/store/avatar-david.jpg',
                ],
                [
                    'quote' => '"The MRR dashboard finally gave us the metrics our investors kept asking for. We can now see expansion MRR, churned MRR, and NRR in real time — from the same tool that does our invoicing. That\'s incredibly valuable."',
                    'name'  => 'Emily Watson',
                    'role'  => 'CFO, EdTech Ventures · Delhi',
                    'img'   => 'assets/store/avatar-emily.jpg',
                ],
            ];
            foreach($reviews as $r): ?>
            <div class="card" style="background:white;display:flex;flex-direction:column;"
                 itemscope itemtype="https://schema.org/Review">
                <div style="display:flex;gap:2px;margin-bottom:1.1rem;" aria-label="5 out of 5 stars">
                    <?php for($i=0;$i<5;$i++): ?>
                    <svg width="15" height="15" fill="#FBBF24" viewBox="0 0 20 20" aria-hidden="true"><path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"/></svg>
                    <?php endfor; ?>
                </div>
                <p itemprop="reviewBody" style="font-style:italic;font-size:0.95rem;line-height:1.75;margin-bottom:1.5rem;color:var(--text-main);flex:1;"><?= $r['quote'] ?></p>
                <div style="display:flex;align-items:center;gap:0.85rem;padding-top:1.1rem;border-top:1px solid var(--border-color);"
                     itemscope itemprop="author" itemtype="https://schema.org/Person">
                    <img src="<?= $r['img'] ?>" alt="<?= $r['name'] ?>" width="42" height="42"
                         style="width:42px;height:42px;border-radius:50%;object-fit:cover;flex-shrink:0;" loading="lazy">
                    <div>
                        <div style="font-weight:700;font-size:0.9rem;color:var(--text-main);" itemprop="name"><?= $r['name'] ?></div>
                        <div style="font-size:0.8rem;color:var(--text-muted);"><?= $r['role'] ?></div>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
</section>

<!-- ========== FAQ ========== -->
<section class="bg-offwhite">
    <div class="container" style="max-width:820px;">
        <div class="section-title">
            <h2>Frequently Asked Questions</h2>
            <p>Everything you need to know about ZYLO Subscription Management Software.</p>
        </div>

        <div style="margin-top:2.5rem;" itemscope itemtype="https://schema.org/FAQPage">
            <?php
            $faqs = [
                ['q'=>'What is subscription management software?',      'a'=>'Subscription management software automates recurring billing — generating invoices on schedule, sending renewal reminders, handling plan changes with prorations, collecting payments, and tracking MRR and churn — eliminating all manual billing work.'],
                ['q'=>'Is ZYLO subscription software free?',            'a'=>'Yes. ZYLO offers a free plan with recurring billing for up to 10 active subscriptions. The Pro plan starts at ₹3,999/month with unlimited subscriptions, automated reminders, MRR/ARR dashboards, churn tracking, and WhatsApp notifications.'],
                ['q'=>'Can ZYLO handle GST on subscription invoices?',  'a'=>'Yes. Every recurring invoice is fully GST-compliant with auto CGST/SGST/IGST split based on the customer\'s state, HSN/SAC codes, and GSTR-ready export. Supports e-Invoice with IRN for eligible businesses.'],
                ['q'=>'Can I manage trial periods and free plans?',     'a'=>'Yes. Configure trial lengths for any plan. Trial customers are tracked separately, receive automated upgrade prompts as the trial expires, and convert to paid subscriptions automatically when they choose a plan.'],
                ['q'=>'Does ZYLO track MRR, ARR, and churn?',          'a'=>'Yes. ZYLO\'s real-time dashboard shows MRR, ARR, new MRR, expansion MRR, churned MRR, and Net Revenue Retention — updated as subscriptions change. No spreadsheets, no waiting for monthly reports.'],
            ];
            foreach($faqs as $i=>$faq): ?>
            <div style="border:1px solid var(--border-color);border-radius:12px;margin-bottom:0.9rem;overflow:hidden;"
                 itemscope itemprop="mainEntity" itemtype="https://schema.org/Question">
                <button onclick="toggleFaq(this)" aria-expanded="<?= $i===0?'true':'false' ?>"
                    style="width:100%;text-align:left;background:white;border:none;padding:1.2rem 1.5rem;font-size:0.97rem;font-weight:600;color:var(--primary-dark);cursor:pointer;display:flex;justify-content:space-between;align-items:center;gap:1rem;">
                    <span itemprop="name"><?= $faq['q'] ?></span>
                    <svg class="faq-icon" width="18" height="18" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true"
                         style="flex-shrink:0;transition:transform 0.3s;<?= $i===0?'transform:rotate(180deg)':'' ?>">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/>
                    </svg>
                </button>
                <div class="faq-body" style="<?= $i===0?'':'display:none;' ?>padding:0 1.5rem 1.25rem;background:white;"
                     itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer">
                    <p itemprop="text" style="color:var(--text-muted);margin:0;line-height:1.75;font-size:0.93rem;"><?= $faq['a'] ?></p>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
</section>

<!-- ========== CTA ========== -->
<section style="text-align:center;padding:6rem 0;background:linear-gradient(135deg,var(--primary) 0%,var(--primary-dark) 100%);">
    <div class="container" style="max-width:700px;margin:0 auto;">
        <h2 style="font-size:2.5rem;color:white;margin-bottom:1.25rem;line-height:1.2;">
            Stop Managing Subscriptions Manually. Let ZYLO Do It.
        </h2>
        <p style="font-size:1.1rem;color:rgba(255,255,255,0.85);margin-bottom:2.5rem;line-height:1.7;">
            Join 10,000+ businesses that bill subscribers automatically with ZYLO. Free plan available — no credit card, no setup fee.
        </p>
        <div style="display:flex;gap:1rem;justify-content:center;flex-wrap:wrap;">
            <a href="contact" class="btn" style="padding:1rem 2.25rem;font-size:1.05rem;background:white;color:var(--primary);border-radius:10px;font-weight:700;">
                Start Free Trial
            </a>
            <a href="https://wa.me/917501137266?text=Hi%2C%20I%20want%20to%20know%20more%20about%20ZYLO%20Subscription%20Management%20Software"
               target="_blank" rel="noopener noreferrer"
               class="btn" style="padding:1rem 2.25rem;font-size:1.05rem;background:#25d366;color:white;border-radius:10px;font-weight:600;border:none;">
                💬 Chat on WhatsApp
            </a>
        </div>
        <p style="color:rgba(255,255,255,0.5);font-size:0.82rem;margin-top:1.5rem;margin-bottom:0;">Free plan · No credit card · Cancel anytime</p>
    </div>
</section>

<script>
function toggleFaq(btn) {
    var body = btn.nextElementSibling;
    var icon = btn.querySelector('.faq-icon');
    var expanded = btn.getAttribute('aria-expanded') === 'true';
    document.querySelectorAll('.faq-body').forEach(function(el){ el.style.display='none'; });
    document.querySelectorAll('[onclick="toggleFaq(this)"]').forEach(function(el){
        el.setAttribute('aria-expanded','false');
        el.querySelector('.faq-icon').style.transform='';
    });
    if (!expanded) {
        body.style.display = 'block';
        btn.setAttribute('aria-expanded','true');
        icon.style.transform = 'rotate(180deg)';
    }
}
</script>

<style>
@media (max-width: 768px) {
    .stats-bar-grid   { grid-template-columns: 1fr 1fr !important; }
    .features-grid    { grid-template-columns: 1fr !important; }
    .perfect-for-grid { grid-template-columns: 1fr !important; }
    .feature-img-right{ order: 0 !important; }
}
</style>

<?php include 'includes/footer.php'; ?>
